### PR TITLE
Jmazzotta patch 1

### PR DESCRIPTION
**Pull request by jmazzotta**

### CODE REVIEW

**Comment by ghost** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [enterprise-graph/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/1d72f733990972de3a4e9b8fc2236a8de4558a88/enterprise-graph/breadcrumb/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/qadlkbh4livh65rgxpza4g6s23_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by ghost** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [enterprise-graph/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/162c210befa4e14acc91316e54144d0e89c102d6/enterprise-graph/breadcrumb/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/hjmrphh2jo5cjd7ni2jbiuxnfh_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by ghost** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [enterprise-graph/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/59250c3885d56f2e532df9aac7ffa8afb1e315a3/enterprise-graph/breadcrumb/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/pbneuszotn2mqsgfuspku256qg_report.html) | [:white_check_mark:](# "Successfully processed") |
| [enterprise-graph/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/59250c3885d56f2e532df9aac7ffa8afb1e315a3/enterprise-graph/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/et5f3yyqgn7dnmqbyfli64jnx7_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Comment by dsindona** [comment]
@jmazzotta @microsteve Do we need to resolve this conflict and get these changes merged? or can @jmazzotta close this PR?

**Comment by ghost** [comment]
## Acrolinx Scorecards

**A minimum Acrolinx score of 80 is required.**

Click the scorecard links for each article to review the Acrolinx feedback on grammar, spelling, punctuation, writing style, and terminology:

| Article | Acrolinx<br>Score | Lowest<br>Category<br>Score | Issues | Scorecard | Processed |
|---------|:--------------:|:--------------------:|:------:|:---------:|:---------:|
| [enterprise-graph/breadcrumb/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/2211afeb0e74b6ac68c0817e8a9bfe75a91466db/enterprise-graph/breadcrumb/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/nu7bnwl5xddgcnc6tpes3xembm_report.html) | [:white_check_mark:](# "Successfully processed") |
| [enterprise-graph/toc.yml](https://github.com/MicrosoftDocs/enterprise-graph-docs-pr/blob/2211afeb0e74b6ac68c0817e8a9bfe75a91466db/enterprise-graph/toc.yml) | 100 | 100 | 0 | [link](https://microsoft-ce-csi.acrolinx.cloud/output/en/jaffshugmsvtcb7mgr3dowkmtp_report.html) | [:white_check_mark:](# "Successfully processed") |

**More info about Acrolinx**

- [Install Acrolinx locally for VSCode](https://review.docs.microsoft.com/en-us/help/contribute/contribute-acrolinx-vscode?branch=master)
- [False positives or issues](https://aka.ms/acrolinxbug)

**Pull request closed without merging**
